export const countries = [
  { name: "العراق", flag: "/flag/iraq.png" },
  { name: "السعودية", flag: "/flag/ksa.png" },
  { name: "الإمارات", flag: "/flag/uae.png" },
  { name: "قطر", flag: "/flag/qa.png" },
  { name: "فلسطين", flag: "/flag/ph.png" },
  { name: "مصر", flag: "/flag/egypt.png" },
  { name: "سوريا", flag: "/flag/sy.png" },
  { name: "العراق", flag: "/flag/iraq.png" },
  { name: "السعودية", flag: "/flag/ksa.png" },
  { name: "الإمارات", flag: "/flag/uae.png" },
  { name: "قطر", flag: "/flag/qa.png" },
  { name: "فلسطين", flag: "/flag/ph.png" },
  { name: "مصر", flag: "/flag/egypt.png" },
  { name: "سوريا", flag: "/flag/sy.png" },
  { name: "العراق", flag: "/flag/iraq.png" },
  { name: "السعودية", flag: "/flag/ksa.png" },
  { name: "الإمارات", flag: "/flag/uae.png" },
  { name: "قطر", flag: "/flag/qa.png" },
  { name: "فلسطين", flag: "/flag/ph.png" },
  { name: "مصر", flag: "/flag/egypt.png" },
  { name: "سوريا", flag: "/flag/sy.png" },
];
