export const countries = [
  { name: "العراق", flag: "https://flagcdn.com/w40/iq.png" },
  { name: "السعودية", flag: "https://flagcdn.com/w40/sa.png" },
  { name: "الإمارات", flag: "https://flagcdn.com/w40/ae.png" },
  { name: "قطر", flag: "https://flagcdn.com/w40/qa.png" },
  { name: "اليمن", flag: "https://flagcdn.com/w40/ye.png" },
  { name: "مصر", flag: "https://flagcdn.com/w40/eg.png" },
  { name: "سوريا", flag: "https://flagcdn.com/w40/sy.png" },
  { name: "أمريكا", flag: "https://flagcdn.com/w40/us.png" },
  { name: "كوريا", flag: "https://flagcdn.com/w40/kr.png" },
  { name: "لبنان", flag: "https://flagcdn.com/w40/lb.png" },
  { name: "ماليزيا", flag: "https://flagcdn.com/w40/my.png" },
  { name: "المكسيك", flag: "https://flagcdn.com/w40/mx.png" },
  { name: "المغرب", flag: "https://flagcdn.com/w40/ma.png" },
  { name: "العراق", flag: "https://flagcdn.com/w40/iq.png" },
  { name: "السعودية", flag: "https://flagcdn.com/w40/sa.png" },
  { name: "الإمارات", flag: "https://flagcdn.com/w40/ae.png" },
  { name: "قطر", flag: "https://flagcdn.com/w40/qa.png" },
  { name: "اليمن", flag: "https://flagcdn.com/w40/ye.png" },
  { name: "مصر", flag: "https://flagcdn.com/w40/eg.png" },
  { name: "سوريا", flag: "https://flagcdn.com/w40/sy.png" },
  { name: "أمريكا", flag: "https://flagcdn.com/w40/us.png" },
  { name: "كوريا", flag: "https://flagcdn.com/w40/kr.png" },
  { name: "لبنان", flag: "https://flagcdn.com/w40/lb.png" },
  { name: "ماليزيا", flag: "https://flagcdn.com/w40/my.png" },
  { name: "المكسيك", flag: "https://flagcdn.com/w40/mx.png" },
  { name: "المغرب", flag: "https://flagcdn.com/w40/ma.png" },
  
];
